---
ansible_connection: netscaler.adc.ssh_netscaler_adc
ansible_user: "{{ nitro_user }}"
ansible_password: "{{ nitro_pass }}"
ansible_python_interpreter: "{{ netscaler_python_path | default('/var/python/bin/python') }}"
